# Generated by Django 4.2.11 on 2024-03-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_text_blog_content_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
